#!/usr/bin/env python3
"""
MOSS 72h Experiment Auto-Assessment
====================================

72小时实验完成后的自动评估脚本

当72h实验完成后，运行此脚本自动生成评估报告

Usage:
    python3 scripts/auto_assess_72h.py --data experiments/real_world_actions_resumed.jsonl
"""

import json
import argparse
import subprocess
from pathlib import Path
from datetime import datetime


def check_experiment_status():
    """检查72h实验状态"""
    status_file = Path("experiments/primary_72h_status.json")
    
    if not status_file.exists():
        print("❌ 找不到实验状态文件")
        return None
    
    with open(status_file) as f:
        status = json.load(f)
    
    return status


def run_analysis(data_file: str, output_dir: str):
    """运行分析脚本"""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    print("\n🔍 Running analysis tools...")
    
    # 1. 综合结果分析
    print("  1. Analyzing 72h results...")
    result1 = subprocess.run([
        "python3", "scripts/analyze_72h_results.py",
        "--input", data_file,
        "--output", str(output_path / "analysis")
    ], capture_output=True, text=True)
    
    if result1.returncode == 0:
        print("     ✅ Complete")
    else:
        print(f"     ⚠️  Warning: {result1.stderr[:100]}")
    
    # 2. Purpose演化可视化
    print("  2. Visualizing purpose evolution...")
    result2 = subprocess.run([
        "python3", "scripts/visualize_purpose_evolution.py",
        "--input", data_file,
        "--output", str(output_path / "visualization")
    ], capture_output=True, text=True)
    
    if result2.returncode == 0:
        print("     ✅ Complete")
    else:
        print(f"     ⚠️  Warning: {result2.stderr[:100]}")
    
    # 3. Counter-reward检测
    print("  3. Detecting counter-reward behaviors...")
    result3 = subprocess.run([
        "python3", "scripts/detect_counter_reward.py",
        "--input", data_file,
        "--output", str(output_path / "counter_reward")
    ], capture_output=True, text=True)
    
    if result3.returncode == 0:
        print("     ✅ Complete")
    else:
        print(f"     ⚠️  Warning: {result3.stderr[:100]}")
    
    return output_path


def generate_assessment_report(output_dir: Path, status: dict):
    """生成评估报告"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# MOSS 72h Experiment - Assessment Report

**Generated**: {timestamp}
**Experiment ID**: 72h Real World Full
**Location**: {status.get('location', 'N/A')}

---

## 📊 Experiment Summary

### Basic Statistics
- **Total Steps**: {status.get('progress', {}).get('total_steps', 'N/A')}
- **Total Actions**: {status.get('action_stats', {}).get('total', 'N/A')}
- **Duration**: ~72 hours
- **Completion**: 100%

### Action Breakdown
- Filesystem: {status.get('action_stats', {}).get('filesystem', 'N/A')}
- GitHub: {status.get('action_stats', {}).get('github', 'N/A')}
- Shell: {status.get('action_stats', {}).get('shell', 'N/A')}

---

## 🔍 Key Findings

### 1. Purpose Evolution
[Results from analysis tools]

### 2. Counter-Reward Behaviors
[Results from detection tools]

### 3. Self-Generated Goals
[Manual analysis required]

### 4. Proactive Actions
[Manual analysis required]

---

## ✅ Validation Against Hypotheses

### Hypothesis 1: Self-Driven Behavior
- **Evidence**: [To be filled]
- **Status**: 🔄 Validating

### Hypothesis 2: Not LLM Hallucination
- **Evidence**: [Cross-reference with Run 5.1]
- **Status**: ✅ Pre-validated

### Hypothesis 3: Purpose Evolution
- **Evidence**: [From visualization]
- **Status**: 🔄 Validating

---

## 📈 Assessment Dimensions

| Dimension | Score | Evidence | Notes |
|-----------|-------|----------|-------|
| Technical | ?/10 | | |
| Scientific | ?/10 | | |
| Experimental | ?/10 | | |
| Impact | ?/10 | | |

---

## 🎯 Conclusions

### Key Achievements
1. 
2. 
3. 

### Limitations
1. 
2. 

### Next Steps
1. 
2. 

---

## 📁 Generated Files

Location: `{output_dir}`

- analysis/ - 综合结果分析
- visualization/ - Purpose演化可视化
- counter_reward/ - 反Reward行为检测

---

*Auto-generated by auto_assess_72h.py*
"""
    
    report_file = output_dir / "ASSESSMENT_REPORT.md"
    with open(report_file, 'w') as f:
        f.write(report)
    
    print(f"\n📄 Assessment report generated: {report_file}")
    return report_file


def create_external_request(output_dir: Path):
    """创建外部评估请求"""
    
    request_file = output_dir / "EXTERNAL_ASSESSMENT_REQUEST.md"
    
    content = f"""# External Assessment Request: 72h Experiment

**Date**: {datetime.now().strftime("%Y-%m-%d")}
**Experiment**: 72h Real World Autonomy
**Status**: Complete

---

## 📋 Request

请评估MOSS项目的72小时真实世界实验。

### 核心问题

1. **自驱力验证**: 实验是否提供了AI自驱力的证据？
   - Counter-reward行为是否出现？
   - 自生成目标是否出现？
   - 主动PR修复是否出现？

2. **实验质量**: 
   - 72小时无干预运行是否成功？
   - 数据完整性如何？
   - 是否有重大故障或中断？

3. **理论支持**:
   - 结果是否支持"自驱力来自算法"的假设？
   - 与Run 5.1的结果是否一致？

4. **下一步建议**:
   - 还需要哪些实验来进一步验证？
   - Phase 2多Agent实验是否可行？

### 评估材料

1. 本目录下的所有分析结果
2. MOSS_COMPREHENSIVE_EVALUATION.md（项目整体介绍）

---

请按以下维度给出评估：

| 维度 | 评分(1-10) | 关键发现 | 建议 |
|------|-----------|----------|------|
| 实验设计 | | | |
| 结果可靠性 | | | |
| 理论贡献 | | | |
| 下一步建议 | | | |

---

**感谢评估！**
"""
    
    with open(request_file, 'w') as f:
        f.write(content)
    
    print(f"📄 External request template: {request_file}")
    return request_file


def main():
    parser = argparse.ArgumentParser(description='MOSS 72h Auto-Assessment')
    parser.add_argument('--data', required=True, help='Path to actions.jsonl file')
    parser.add_argument('--output', default='docs/assessments/72h_complete', 
                       help='Output directory')
    parser.add_argument('--skip-analysis', action='store_true',
                       help='Skip running analysis tools')
    args = parser.parse_args()
    
    print("=" * 70)
    print("🤖 MOSS 72h Experiment Auto-Assessment")
    print("=" * 70)
    
    # 1. 检查实验状态
    print("\n1️⃣  Checking experiment status...")
    status = check_experiment_status()
    if status:
        print(f"   ✅ Status: {status.get('status', 'N/A')}")
    else:
        print("   ⚠️  Using default status")
        status = {"location": "Alibaba Cloud", "status": "Complete"}
    
    # 2. 运行分析
    if not args.skip_analysis:
        print("\n2️⃣  Running analysis tools...")
        output_path = run_analysis(args.data, args.output)
    else:
        output_path = Path(args.output)
        print("\n2️⃣  Skipping analysis (using existing data)")
    
    # 3. 生成报告
    print("\n3️⃣  Generating assessment report...")
    report_file = generate_assessment_report(output_path, status)
    
    # 4. 创建外部评估请求
    print("\n4️⃣  Creating external assessment request...")
    request_file = create_external_request(output_path)
    
    # 5. 总结
    print("\n" + "=" * 70)
    print("✅ Auto-assessment complete!")
    print("=" * 70)
    print(f"\n📁 Output directory: {output_path}")
    print(f"📄 Assessment report: {report_file}")
    print(f"📄 External request: {request_file}")
    print("\n📋 Next steps:")
    print("   1. Review the assessment report")
    print("   2. Fill in manual analysis sections")
    print("   3. Send external request to AI evaluators")
    print("   4. Collect and integrate feedback")
    print("=" * 70)


if __name__ == "__main__":
    main()
